### ISSUE TITLE
`dotnet aws delete-deployment` fails if resource has been added to a security group

### ISSUE THREAD

**Issue by ppittle** [aws/aws-dotnet-deploy#144]
**Describe the bug**
I deployed a [Console Application that reads from a Database](https://github.com/aws/aws-dotnet-deploy/tree/main/testapps/ContosoUniversityBackendService) to a Fargate Service.

After it was deployed I updated my RDS's Security Group to allow the new Application to read the database.

I then ran `dotnet aws delete-deployment` and got this error message:

```
03/15/2021 15:46:18 | DELETE_FAILED        | AWS::CloudFormation::Stack               | ContosoFargateService2
Unhandled exception: AWS.Deploy.CLI.FailedToDeleteException: The stack ContosoFargateService2 is in a failed state. You may need to delete it from the AWS Console.
   at AWS.Deploy.CLI.Commands.DeleteDeploymentCommand.WaitForStackDelete(String stackName) in C:\codebuild\tmp\output\src000293299\src\src\AWS.Deploy.CLI\Commands\DeleteDeploymentCommand.cs:line 122
   at AWS.Deploy.CLI.Commands.DeleteDeploymentCommand.ExecuteAsync(String stackName) in C:\codebuild\tmp\output\src000293299\src\src\AWS.Deploy.CLI\Commands\DeleteDeploymentCommand.cs:line 73
   at AWS.Deploy.CLI.Program.<>c.<<Main>b__4_2>d.MoveNext() in C:\codebuild\tmp\output\src000293299\src\src\AWS.Deploy.CLI\Program.cs:line 217
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
```

Cloud Formation in AWS Console shows:

![image](https://user-images.githubusercontent.com/1190907/111232570-940fde80-85a8-11eb-9b3b-0aafe68e7dda.png)

My Fargate Task Definition has been deleted which is good.  But the CloudFormation stack still exists and is in a delete failed state.

**Expected behavior**
My application and related AWS Resource to be successfully deleted and no error message should be displayed.

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] `0.1.1-beta.20210315205437.06db70a`
 - Include the output of `dotnet --info` `5.0.201`
 - OS Info: `Windows 10`

---

This is a :bug: bug report

**Comment by philasmar** [comment]
This should no longer be an issue as you can add additional security groups to your deployment instead of the other way around.
