### ISSUE TITLE
Delete Scheduled Task fails: Cluster can't be deleted while Tasks are active

### ISSUE THREAD

**Issue by ppittle** [aws/aws-dotnet-deploy#145]
**Describe the bug**
Deploying a console application to a Fargate Scheduled Tasks and then deleting it fails.  The cli command takes a very long time (20+ minutes) and the Cloud Formation stack is in delete_failed state.

![image](https://user-images.githubusercontent.com/1190907/111234974-f5d24780-85ac-11eb-8332-0614e4fd1adc.png)

Fortunately it is _not_ listed in `dotnet aws list-deployments`.

**To Reproduce**
1 `mkdir example & cd example`
1.. `dotnet new console`
2. `dotnet aws deploy`
3. Select `2` for Schedule Task
4. Accept defaults and deploy
5.Run `dotnet delete-deployment example`

**Logs**
```
TestTaskScheduled: deleting...
03/15/2021 16:25:31 | DELETE_IN_PROGRESS   | AWS::CDK::Metadata                       | CDKMetadata
03/15/2021 16:25:31 | DELETE_IN_PROGRESS   | AWS::IAM::Policy                         | TaskDefinitionExecutionRoleDefaultPolicy1F3406F5
03/15/2021 16:25:31 | DELETE_IN_PROGRESS   | AWS::Events::Rule                        | FargateServiceScheduledEventRule7F21314E
03/15/2021 16:25:31 | DELETE_IN_PROGRESS   | AWS::IAM::Policy                         | TaskDefinitionEventsRoleDefaultPolicyD432DADD
03/15/2021 16:25:32 | DELETE_COMPLETE      | AWS::IAM::Policy                         | TaskDefinitionEventsRoleDefaultPolicyD432DADD
03/15/2021 16:25:32 | DELETE_COMPLETE      | AWS::IAM::Policy                         | TaskDefinitionExecutionRoleDefaultPolicy1F3406F5
03/15/2021 16:25:32 | DELETE_COMPLETE      | AWS::CDK::Metadata                       | CDKMetadata
03/15/2021 16:26:31 | DELETE_COMPLETE      | AWS::Events::Rule                        | FargateServiceScheduledEventRule7F21314E
03/15/2021 16:26:32 | DELETE_IN_PROGRESS   | AWS::IAM::Role                           | TaskDefinitionEventsRole1DC90F44
03/15/2021 16:26:32 | DELETE_IN_PROGRESS   | AWS::EC2::SecurityGroup                  | TaskDefinitionSecurityGroup16A8B1FE
03/15/2021 16:26:32 | DELETE_IN_PROGRESS   | AWS::ECS::TaskDefinition                 | TaskDefinitionB36D86D9
03/15/2021 16:26:32 | DELETE_IN_PROGRESS   | AWS::ECS::Cluster                        | ClusterEB0386A7
03/15/2021 16:26:33 | DELETE_FAILED        | AWS::ECS::Cluster                        | ClusterEB0386A7
03/15/2021 16:26:34 | DELETE_COMPLETE      | AWS::IAM::Role                           | TaskDefinitionEventsRole1DC90F44
03/15/2021 16:26:34 | DELETE_COMPLETE      | AWS::ECS::TaskDefinition                 | TaskDefinitionB36D86D9
03/15/2021 16:26:35 | DELETE_IN_PROGRESS   | AWS::IAM::Role                           | TaskRole30FC0FBB
03/15/2021 16:26:35 | DELETE_IN_PROGRESS   | AWS::IAM::Role                           | TaskDefinitionExecutionRole8D61C2FB
03/15/2021 16:26:35 | DELETE_SKIPPED       | AWS::Logs::LogGroup                      | TaskDefinitionContainerLogGroup4D0A87C1
03/15/2021 16:26:36 | DELETE_COMPLETE      | AWS::IAM::Role                           | TaskRole30FC0FBB
03/15/2021 16:26:36 | DELETE_COMPLETE      | AWS::IAM::Role                           | TaskDefinitionExecutionRole8D61C2FB
03/15/2021 16:44:17 | DELETE_FAILED        | AWS::EC2::SecurityGroup                  | TaskDefinitionSecurityGroup16A8B1FE
03/15/2021 16:44:18 | DELETE_FAILED        | AWS::CloudFormation::Stack               | TestTaskScheduled
Unhandled exception: AWS.Deploy.CLI.FailedToDeleteException: The stack TestTaskScheduled is in a failed state. You may need to delete it from the AWS Console.
   at AWS.Deploy.CLI.Commands.DeleteDeploymentCommand.WaitForStackDelete(String stackName) in C:\codebuild\tmp\output\src000293299\src\src\AWS.Deploy.CLI\Commands\DeleteDeploymentCommand.cs:line 122
   at AWS.Deploy.CLI.Commands.DeleteDeploymentCommand.ExecuteAsync(String stackName) in C:\codebuild\tmp\output\src000293299\src\src\AWS.Deploy.CLI\Commands\DeleteDeploymentCommand.cs:line 73
   at AWS.Deploy.CLI.Program.<>c.<<Main>b__4_2>d.MoveNext() in C:\codebuild\tmp\output\src000293299\src\src\AWS.Deploy.CLI\Program.cs:line 217
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Invocation.CommandHandler.GetResultCodeAsync(Object value, InvocationContext context)
   at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__21_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass25_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass23_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__11_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__10_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Expected behavior**
Deployment should delete without error.

**Screenshots**
![image](https://user-images.githubusercontent.com/1190907/111235456-ec95aa80-85ad-11eb-9340-c3b82cbb4070.png)

**Environment (please complete the following information):**
 - CLI Version: [eg. 1.0.0] `0.1.1-beta.20210315205437.06db70a`
 - Include the output of `dotnet --info` `5.0.201`
 - OS Info: `Windows 10`

**Additional context**

---

This is a :bug: bug report

**Comment by philasmar** [comment]
This is no longer an issue.
