### ISSUE TITLE
Support for Jakarta region

### ISSUE THREAD

**Issue by awschristou** [aws/aws-dotnet-deploy#430]
**Describe the bug**
I am unable to use the deploy cli to publish my application to the new Jakarta region. At this time, the region does not support Beanstalk, but does support CloudFormation, ECS, and ECR.

**To Reproduce**
1. Enable Jakarta region in my account
2. Set up STS global tokens to work with this region - https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_enable-regions.html#sts-regions-manage-tokens
3. set up credentials for the Jakarta region
```
[myprofile]
aws_access_key_id=xxx
aws_secret_access_key=xxx
region=ap-southeast-3
```
4. create asp net core application
5. run `dotnet aws deploy --profile myprofile --region ap-southeast-3` from the folder containing the csproj file
6. get error

**Logs**
Logs obtained from CLI output.
```
C:\...\MyAspNetCoreApp>dotnet aws deploy
AWS .NET deployment tool for deploying .NET Core applications to AWS.
Project Home: https://github.com/aws/aws-dotnet-deploy

Configuring AWS Credentials using AWS SDK credential search.
Configuring AWS region using AWS SDK region search to ap-southeast-3.
Unhandled exception.  This is a bug.  Please copy the stack trace below and file a bug at https://github.com/aws/aws-dotnet-deploy.
.NET Core Solution Stack doesn't exist.
   at AWS.Deploy.Orchestration.Data.AWSResourceQueryer.GetLatestElasticBeanstalkPlatformArn() in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs:line 367
   at AWS.Deploy.Orchestration.Orchestrator.GetReplacements() in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.Orchestration/Orchestrator.cs:line 124
   at AWS.Deploy.Orchestration.Orchestrator.GenerateDeploymentRecommendations() in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.Orchestration/Orchestrator.cs:line 88
   at AWS.Deploy.CLI.Commands.DeployCommand.GenerateDeploymentRecommendations(Orchestrator orchestrator, String deploymentProjectPath) in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.CLI/Commands/DeployCommand.cs:line 261
   at AWS.Deploy.CLI.Commands.DeployCommand.InitializeDeployment(String stackName, UserDeploymentSettings userDeploymentSettings, String deploymentProjectPath) in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.CLI/Commands/DeployCommand.cs:line 161
   at AWS.Deploy.CLI.Commands.DeployCommand.ExecuteAsync(String stackName, String deploymentProjectPath, UserDeploymentSettings userDeploymentSettings) in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.CLI/Commands/DeployCommand.cs:line 98
   at AWS.Deploy.CLI.Commands.CommandFactory.<BuildDeployCommand>b__37_0(DeployCommandHandlerInput input) in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.CLI/Commands/CommandFactory.cs:line 229
```

**Expected behavior**
1. Tooling works for this region just like any other region
2. Error handling and error message (for future regions) is clear about the problem and to file an issue in this repo.

**Environment (please complete the following information):**
 - CLI Version: 0.32.13+5eb08ccbd0
 - OS Info: Windows 10

**Additional context**

Related: The AWS Toolkit for Visual Studio isn't able to publish to Jakarta as a result -- https://github.com/aws/aws-toolkit-visual-studio/issues/206

---

This is a :bug: bug report

**Comment by philasmar** [comment]
The latest release 0.33.9 addresses this issue. The error messaging has been improved, and the application does not fail directly. It will only fail after you select the beanstalk recipe, if beanstalk is not enabled in that region. The message for that failure has also been improved.
