### ISSUE TITLE
Exception when running list-deployments from CLI

### ISSUE THREAD

**Issue by iamtreble** [aws/aws-dotnet-deploy#441]
Stacktrace:

Unhandled exception.  This is a bug.  Please copy the stack trace below and file a bug at https://github.com/aws/aws-dotnet-deploy.
User: arn:aws:iam::x:user/y is not authorized to perform: cloudformation:DescribeStacks with an explicit deny in an identity-based policy
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionStream(IRequestContext requestContext, IWebResponseData httpErrorResponse, HttpErrorResponseException exception, Stream responseStream)
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleExceptionAsync(IExecutionContext executionContext, HttpErrorResponseException exception)
   at Amazon.Runtime.Internal.ExceptionHandler`1.HandleAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.ProcessExceptionAsync(IExecutionContext executionContext, Exception exception)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.EndpointDiscoveryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.CloudFormation.Model.DescribeStacksPaginator.Amazon.Runtime.IPaginator<Amazon.CloudFormation.Model.DescribeStacksResponse>.PaginateAsync(CancellationToken cancellationToken)+MoveNext()
   at Amazon.CloudFormation.Model.DescribeStacksPaginator.Amazon.Runtime.IPaginator<Amazon.CloudFormation.Model.DescribeStacksResponse>.PaginateAsync(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Amazon.Runtime.PaginatedResultKeyResponse`2.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Amazon.Runtime.PaginatedResultKeyResponse`2.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Amazon.Runtime.PaginatedResultKeyResponse`2.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at System.Linq.AsyncEnumerable.<ToListAsync>g__Core|620_0[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken) in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\ToList.cs:line 27
   at AWS.Deploy.Orchestration.Data.AWSResourceQueryer.GetCloudFormationStacks() in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.Orchestration/Data/AWSResourceQueryer.cs:line 421
   at AWS.Deploy.Orchestration.Utilities.DeployedApplicationQueryer.GetExistingDeployedApplications() in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.Orchestration/Utilities/DeployedApplicationQueryer.cs:line 54
   at AWS.Deploy.CLI.Commands.ListDeploymentsCommand.ExecuteAsync() in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.CLI/Commands/ListDeploymentsCommand.cs:line 29
   at AWS.Deploy.CLI.Commands.CommandFactory.<BuildListCommand>b__39_0(ListCommandHandlerInput input) in /codebuild/output/src369531262/src/codestar-connections.us-west-2.amazonaws.com/git-http/393431854674/us-west-2/eb780f07-2f46-42e0-9c15-df6f00fe3c1c/aws/aws-dotnet-deploy/src/AWS.Deploy.CLI/Commands/CommandFactory.cs:line 371
Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken)
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)

**Comment by philasmar** [comment]
Hello,
The stack trace is saying that the AWS credentials/Profile/Assumed Role does not have the right permissions to perform the task. The exact permission it is complaining about is: `cloudformation:DescribeStacks`.
Make sure to add that permission and try again.
