### ISSUE TITLE
Don't show recommendations for services not supported in a region

### ISSUE THREAD

**Issue by awschristou** [aws/aws-dotnet-deploy#467]
**Is your feature request related to a problem? Please describe.**

I tried to publish my application to App Runner in `Canada (Central)`, and got the following failure (below). The root cause was that App Runner is not available in this region. 

```
MyAspNetCoreApp: deploying...
MyAspNetCoreApp: creating CloudFormation changeset...

 ❌  MyAspNetCoreApp failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::AppRunner::Service]
    at Request.extractError (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\protocol\query.js:50:29)
    at Request.callListeners (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:688:14)
    at Request.transition (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\request.js:690:12)
    at Request.callListeners (C:\Users\xxxxx\.aws-dotnet-deploy\node_modules\aws-cdk\node_modules\aws-sdk\lib\sequential_executor.js:116:18) {
  code: 'ValidationError',
  time: 2022-03-04T00:43:56.128Z,
  requestId: '0a23f070-a4e7-418d-9e3c-107391d9d483',
  statusCode: 400,
  retryable: false,
  retryDelay: 832.9546585670413
}
Template format error: Unrecognized resource types: [AWS::AppRunner::Service]
```

**Describe the solution you'd like**

I should not see recommendations for services that are not available in the region I am trying to deploy to.

**Additional context**
- Deploy CLI version 0.34.5

---

This is a :rocket: feature request

**Comment by normj** [comment]
Since there isn't a good programmatic way to determine what services are in what region from the deployment tool this isn't something we are going to address.
