### ISSUE TITLE
Unhandled exception when deploy --project-path is not valid/found

### ISSUE THREAD

**Issue by floralph** [aws/aws-dotnet-deploy#515]
**Describe the bug**
I accidentally entered an invalid path for deploy --project-path which resulted in "Unhandled exception.  This is a bug."

**To Reproduce**

```
PS C:\Users\floralph\source\aws-dotnet-deploy\src\AWS.Deploy.CLI\bin\Debug\netcoreapp3.1> .\AWS.Deploy.CLI.exe deploy --project-path c:\user\floralph\source\scratch\webapplication1
AWS .NET deployment tool for deploying .NET Core applications to AWS.
Project Home: https://github.com/aws/aws-dotnet-deploy

Unhandled exception.  This is a bug.  Please copy the stack trace below and file a bug at https://github.com/aws/aws-dotnet-deploy.
Could not find a part of the path 'c:\user\floralph\source\scratch\webapplication1'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
   at AWS.Deploy.Common.IO.DirectoryManager.GetFiles(String path, String searchPattern, SearchOption searchOption) in C:\Users\floralph\source\aws-dotnet-deploy\src\AWS.Deploy.Common\IO\DirectoryManager.cs:line 42
   at AWS.Deploy.CLI.Utilities.ProjectParserUtility.Parse(String projectPath) in C:\Users\floralph\source\aws-dotnet-deploy\src\AWS.Deploy.CLI\Utilities\ProjectParserUtility.cs:line 44
   at AWS.Deploy.CLI.Commands.CommandFactory.<BuildDeployCommand>b__38_0(DeployCommandHandlerInput input) in C:\Users\floralph\source\aws-dotnet-deploy\src\AWS.Deploy.CLI\Commands\CommandFactory.cs:line 174
```

**Logs**
Logs obtained from CLI output.

**Expected behavior**
No unhandled exception and stack output, just an error message that the path was not found.

**Screenshots**

**Screen recording**
If applicable, add screen recording to help explain your problem.

**Environment (please complete the following information):**
 - CLI Version: 0.39.8
 - Include the output of `dotnet --info`
 - OS Info: Windows 10

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  2.1.403 [C:\Program Files\dotnet\sdk]
  2.1.526 [C:\Program Files\dotnet\sdk]
  3.1.418 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  5.0.407 [C:\Program Files\dotnet\sdk]
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.24 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Additional context**

---

This is a :bug: bug report

**Comment by 96malhar** [comment]
Thank you, @floralph, for filing this bug report. 
We have a [PR](https://github.com/aws/aws-dotnet-deploy/pull/533) out for this and the fix will be released soon,

**Comment by 96malhar** [comment]
Close this issue as the fix has been released.
