### ISSUE TITLE
Publish failures when user profile path contains a space

### ISSUE THREAD

**Issue by awschristou** [aws/aws-dotnet-deploy#579]
**Describe the bug**
A bug was reported on the Publish to AWS experience in the AWS Toolkit for Visual Studio. Deployments will fail for (Windows) users with a space in their user profile path.

Issue: https://github.com/aws/aws-toolkit-visual-studio/issues/255

**To Reproduce**
1. Have a Windows user profile path containing a space (eg: `c:\users\foo bar\`)
2. Open a deployable project in Visual Studio
3. Right click on the project in solution explorer, select "Publish to AWS" 
4. Try to publish the project

**Logs**

```

Generating AWS Cloud Development Kit (AWS CDK) deployment project
Using bootstrapping template from C:\\Users\\Marco Ma\\.aws-dotnet-deploy\\CDKBootstrapTemplate.yaml
Unhandled exception. Amazon.JSII.Runtime.JsiiException: Child process exited unexpectedly!
   at Amazon.JSII.Runtime.Services.Runtime.ReadResponse()
   at Amazon.JSII.Runtime.Services.Client.ReceiveResponse[TResponse]()
   at Amazon.JSII.Runtime.Services.Client.Hello()
   at Amazon.JSII.Runtime.Services.ServiceContainer.BuildServiceProvider(ILoggerFactory loggerFactoryOverride)
   at Amazon.JSII.Runtime.Services.ServiceContainer.<>c.<.cctor>b__8_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Amazon.JSII.Runtime.Services.ServiceContainer.get_ServiceProvider()
   at Amazon.JSII.Runtime.Deputy.JsiiTypeAttributeBase.Load(Assembly assembly)
   at Amazon.JSII.Runtime.Deputy.JsiiTypeAttributeBase.Load(Assembly assembly)
   at Amazon.JSII.Runtime.Deputy.DeputyBase..ctor(DeputyProps props)
   at Constructs.Construct..ctor(DeputyProps props)
   at Amazon.CDK.Stage..ctor(DeputyProps props)
   at Amazon.CDK.App..ctor(IAppProps props)
   at CronoDemo.Program.Main(String[] args) in C:\Users\Marco Ma\.aws-dotnet-deploy\Projects\0weos3hc\Program.cs:line 17
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\Users\Marco'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Subprocess exited with error 3762504530


CronoDev could not be published as ASP.NET Core App to Amazon ECS using Fargate: The AWS CDK Bootstrap, which is the process of provisioning initial resources for the deployment environment, has failed. Please review the output above for additional details [and check out our troubleshooting guide for the most common failure reasons]. You can learn more about CDK bootstrapping at https://docs.aws.amazon.com/cdk/v2/guide/bootstrapping.html.
CronoDemo failed to publish to AWS.
```

**Expected behavior**
Publish should work the same for users whether or not their user profile folder contains a space.

**Environment (please complete the following information):**

- Windows Version: 10
- Visual Studio Version: 2022
- AWS Toolkit for Visual Studio Version: 1.29.0.0
- CDK Version: 2.25.0 (build ae1cb4b)

---

This is a :bug: bug report

**Comment by 96malhar** [comment]
This issue has been solved with the merging of https://github.com/aws/aws-dotnet-deploy/pull/617. 
Kindly refer to https://aws.github.io/aws-dotnet-deploy/docs/getting-started/custom-workspace/ for a workaround
