### ISSUE TITLE
Can't deploy from Visual Studio 2022 (64 bit) Version 17.2.6

### ISSUE THREAD

**Issue by purplesmash** [aws/aws-dotnet-deploy#677]
### Describe the bug

Following the latest update when I click Publish to AWS whilst I can select a new target or publish to an existing target the ability to edit the Target Configuration is not available and the details of the configuration is not available. The publish button is shown but does nothing on click.

I have a number of asp.net (version 6) applications that I have deployed to ECS using AWS Fargate but I am unable push updates through Visual Studio and cannot deploy a new service either.

<img width="926" alt="image" src="https://user-images.githubusercontent.com/28702186/180397168-77357645-bcf9-486b-9121-8a1387888468.png">

### Expected Behavior

The configuration is displayed and the edit button is present to allow me to configure the deployment

### Current Behavior

The configuration is empty and the edit button is not displayed (see image in the description)

### Reproduction Steps

Right click on the project to deploy and select Publish to AWS. The Publish to Existing Target is displayed but the configuration is missing and the publish button does not do anything. Also publish to new target behaves in the same way.

### Version used

1.0.3

### Operating System and version

Windows 11

**Comment by purplesmash** [comment]
From the AWSToolKit visual studio logs


Status: 500
Response: 
{"ErrorCode":"UnexpectedError","Message":"Unexpected character encountered while parsing value: s. Path \u0027\u0027, line 0, position 0.","ProcessExitCode":null}
   at AWS.Deploy.ServerMode.Client.RestAPIClient.<SetDeploymentTargetAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<InvokeSetDeploymentTargetAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.DeployToolController.<SetDeploymentTargetAsync>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Amazon.AWSToolkit.Publish.ViewModels.PublishToAwsDocumentViewModel.<SetDeploymentTargetAsync>d__179.MoveNext()
2022-07-22 13:39:09,100 [58] ERROR Amazon.AWSToolkit.Publish.Views.PublishToAwsDocumentControl - Error reloading configuration details
HTTP Response: 

{"ErrorCode":"UnexpectedError","Message":"Unexpected character encountered while parsing value: s. Path \u0027\u0027, line 0, position 0.","ProcessExitCode":null}

AWS.Deploy.ServerMode.Client.ApiException: The HTTP status code of the response was not expected (500).

**Comment by purplesmash** [comment]
I have put the issue into the AWSToolKit page instead as that is more appropriate
