### ISSUE TITLE
 Issue while deploying ASP.Net Core Project on AWS Elasticbeanstalk

### ISSUE THREAD

**Issue by ashovlin** [aws/aws-dotnet-deploy#755]
Tracking issue on our side for https://github.com/aws/aws-toolkit-visual-studio/issues/309

### Describe the bug

Step 1:- I created a simple ASP.Net Core Web App using Visual Studio 2022
Step 2:- Installed AWS toolkit
Step3:- Selected Publish to AWS for deploying my application on my free AWS tier using Elasticbeanstalk
Step 4:- I get the following error on the 3rd Step i.e. on Deploying AWS CDK Project :

AWSDeploymentProject: deploying...
[0%] start: Publishing 73645f7c905524d6ca666eae7e1e2a7f1bca1d4062451cd2eb619d2d2f7ec4ec:712088662267-eu-central-1
[0%] start: Publishing b634beaf9192c9e30537653615f0e0f9c3d21b3ab410d6ca555b2ea7fd8ce062:712088662267-eu-central-1
[50%] fail: Socket timed out without establishing a connection
[100%] fail: Socket timed out without establishing a connection

❌ AWSDeploymentProject failed: Error: Failed to publish one or more assets. See the error messages above for more information.
at publishAssets (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\util\asset-publishing.ts:60:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at CloudFormationDeployments.publishStackAssets (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\api\cloudformation-deployments.ts:572:7)
at CloudFormationDeployments.deployStack (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\api\cloudformation-deployments.ts:419:7)
at deployStack2 (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\cdk-toolkit.ts:264:24)
at C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\deploy.ts:39:11
at run (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\p-queue\dist\index.js:163:29)

❌ Deployment failed: Error: Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.
at deployStacks (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\deploy.ts:61:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at CdkToolkit.deploy (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\cdk-toolkit.ts:338:7)
at initCommandLine (C:\Users\ssaty\AppData\Local\npm-cache_npx\e72b144743208263\node_modules\aws-cdk\lib\cli.ts:364:12)

Stack Deployments Failed: Error: Failed to publish one or more assets. See the error messages above for more information.

AWSDeploymentProject could not be published as ASP.NET Core App to AWS Elastic Beanstalk on Windows: We had an issue deploying your application to AWS. Check the deployment output for more details. Deployment took 124.84s.
AWSDeploymentProject failed to publish to AWS.

Note : The IAM user has administrator privileges.

Any help would be appreciated.

### Version used

UNKNOWN

### Operating System and version

UNKNOWN

**Comment by ashishdhingra** [comment]
Requested more information from user at https://github.com/aws/aws-toolkit-visual-studio/issues/309

**Comment by ashishdhingra** [comment]
Related issue https://github.com/aws/aws-toolkit-visual-studio/issues/309 closed as stale.
