### ISSUE TITLE
dotnet aws deploy error

### ISSUE THREAD

**Issue by jjbrooks13** [aws/aws-dotnet-deploy#766]
### Describe the bug

Unhandled exception.  This is a bug.  Please copy the stack trace below and file a bug at https://github.com/aws/aws-dotnet-deploy.
No recommendations available for user to select
   at AWS.Deploy.CLI.ConsoleUtilities.AskToChooseRecommendation(IList`1 recommendations) in C:\build\src\AWS.Deploy.CLI\ConsoleUtilities.cs:line 121
   at AWS.Deploy.CLI.Commands.DeployCommand.GetSelectedRecommendation(DeploymentSettings deploymentSettings, List`1 recommendations) in C:\build\src\AWS.Deploy.CLI\Commands\DeployCommand.cs:line 554
   at AWS.Deploy.CLI.Commands.DeployCommand.InitializeDeployment(String cloudApplicationName, DeploymentSettings deploymentSettings, String deploymentProjectPath) in C:\build\src\AWS.Deploy.CLI\Commands\DeployCommand.cs:line 246
   at AWS.Deploy.CLI.Commands.DeployCommand.ExecuteAsync(String applicationName, String deploymentProjectPath, SaveSettingsConfiguration saveSettingsConfig, DeploymentSettings deploymentSettings) in C:\build\src\AWS.Deploy.CLI\Commands\DeployCommand.cs:line 118
   at AWS.Deploy.CLI.Commands.CommandFactory.<BuildDeployCommand>b__45_0(DeployCommandHandlerInput input) in C:\build\src\AWS.Deploy.CLI\Commands\CommandFactory.cs:line 261

### Expected Behavior

Deploy

### Current Behavior

Errors out

### Reproduction Steps

C:\Work\Code\AMPS\Code\App\AMPSServer>dotnet aws deploy
AWS .NET deployment tool for deploying .NET Core applications to AWS.
Project Home: https://github.com/aws/aws-dotnet-deploy

Configuring AWS Credentials using AWS SDK credential search.
Configuring AWS region using AWS SDK region search to us-east-1.

### Version used

1.12.3+9b8eed77e3

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Hi @jjbrooks13,

Good morning.

Please advise the following:
- If you have evaluated the prerequisites mentioned at https://aws.github.io/aws-dotnet-deploy/docs/getting-started/pre-requisites/.
- What is your application type?
- Could you please share the sample code solution to reproduce the issue? The stack trace points to failure at `DeployCommand.GetSelectedRecommendation()`, so it might be the case that your application type if not compatible with the supported recommendations.

Thanks,
Ashish
